### ISSUE TITLE
Font names with ' ' character crashes the program

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [Whirlpool-Programmer/WhirlEdit#3]
when you enter a font name which has the space character ` ` in it..
The program crashes as ` ` separates different `keywords` defining the font..

EXAMPLE:
`Cascadia Code 12`
here.. `cascadia code` is the font name and `12` is the size..
likewise.. Tkinter makes it like this:
```yaml
FONT_NAME : Cascadia
FONT_SIZE : Code
OTHER_ARGUMENTS : 12
```
so.. as you can guess.. code is not an `int`!

what is the possible fix?
--> replace ` ` in the font name by an "escape" charater which is `\ `
